### ISSUE TITLE
Python packaging

### ISSUE THREAD

**Issue by cthoyt** [v0lta/jaxlets#3]
hey moritz, do you want me to make a PR to put this all in a pip-installable python package?

**Comment by v0lta** [comment]
I would love it if you did that. In that case I would also want to buy you a coffe and learn hot it's done.

**Comment by cthoyt** [comment]
I'd be happy to go over all of it with you. There's also this youtube seminar i did recently https://www.youtube.com/watch?v=lo_g-GbYtaA&t=6540s and a few posts on my blog about different parts (pretty similar to the youtube video, just as text):

1. https://cthoyt.com/2020/06/03/how-to-code-with-me-organization.html
2. https://cthoyt.com/2020/06/11/click.html
3. https://cthoyt.com/2020/04/25/how-to-code-with-me-flake8.html

**Comment by cthoyt** [comment]
Please put comments in the PR about anything you don't understand and I will explain!
